### ISSUE TITLE
Usar favicon de javascript.com

### ISSUE THREAD

**Issue by paulomcnally** [js-ni/ni#10]
Se requiere cambiar el favicon de react que viene en el proyecto.

**Comment by burzumumbra** [comment]
![js_icon](https://user-images.githubusercontent.com/4171009/31746482-fd8c683c-b424-11e7-9074-93c02ce604ac.png)

## Me tomo una hora esta propuesta para el favicon 100% legit.

**Comment by burzumumbra** [comment]
Ya siendo serio, me puedo sacar el favicon en estos días (antes del sabado) pero primero seria que en el otro issue respondan si se sacan el logo de ni.js.org.

**Comment by paulomcnally** [comment]
El logo es para el home, no necesariamente debe ser parecido al favicon, la prupuesta actual no es la final?

**Comment by burzumumbra** [comment]
No, esta no es propuesta final, solo era la divertida. Entre mañana y el viernes subo una propuesta mas seria para Favicon.

**Comment by oscarmcm** [comment]
@burzumumbra dale 👍

**Comment by burzumumbra** [comment]
Adjunto mis propuestas de Favicon.
![js ni-01](https://user-images.githubusercontent.com/4171009/31836265-e86b80aa-b591-11e7-945a-fa945e480cda.png)
![js ni-04](https://user-images.githubusercontent.com/4171009/31836266-e8845454-b591-11e7-966a-031fc0ca60ae.png)
![js ni-05](https://user-images.githubusercontent.com/4171009/31836267-e89ddfe6-b591-11e7-96f4-53f2ff10cb21.png)
![js ni-06](https://user-images.githubusercontent.com/4171009/31836268-e8b898c2-b591-11e7-8a8a-bf6a47daf03c.png)

**Comment by paulomcnally** [comment]
Voto por este:
![31836266-e8845454-b591-11e7-966a-031fc0ca60ae](https://user-images.githubusercontent.com/181533/31909489-8b1140ee-b7f7-11e7-939a-246b3370c11f.png)

**Comment by burzumumbra** [comment]
@paulomcnally dale en la mañana te pongo el pull request, que hoy no me da chance ya.

**Comment by paulomcnally** [comment]
https://github.com/js-ni/ni/pull/12
