### ISSUE TITLE
debate: El rumbo de ni.js.org

### ISSUE THREAD

**Issue by paulomcnally** [js-ni/ni#13]
Con @hosmelq hablábamos hace unos años de un sistema tipo foro para que usuarios se registraran e hicieran sus preguntas.

Eso no se hizo debido a falta de tiempo entre los que henchiríamos mano en ello.

Propongo que nos quedemos con algo básico con ReactJS (Landing page) y rellenarlo con feed del blog en Medium, eventos desde la página en Facebook, fotos desde galerias de fotos en facebook o instagram.

Que opinan? @js-ni/members ?

**Comment by carloslenondavis** [comment]
Suena excelente la idea. Además de medium, se puede agregar una sección que cargue los repo de github y asi los usuarios puedan acceder a código y ejemplos desde el sitio entre otras info. Yo me apunto.

**Comment by RafaBenard** [comment]
Para cuando un curso de JS? :)

**Comment by hosmelq** [comment]
Me parece bien. Si vamos a dejarlo así me puedo encargar de limpiar el repo del sitio, lo podría mover a [Next](https://github.com/zeit/next.js/) o [Gatsby](https://www.gatsbyjs.org/)

**Comment by paulomcnally** [comment]
@clenondavis me parece genial también lo que mencionas. https://github.com/js-ni/ni/issues/17

**Comment by paulomcnally** [comment]
@hosmelq opino que mientras más lite mejor, NextJS no nos da demasiado para lo poco que requerimos? **Gatsby** lo desconozco.

**Comment by leftdevel** [comment]
Sería bueno algo en concreto orientado a node y que tenga que ver con Nicaragua. Personalmente me inclino en contra de hacer un foro, creo que en internet ya hay cientos de recursos para responder dudas.

Me gusta más la idea de la integración con medium, eventos de facebook, galería de fotos, más lo que dice @clenondavis, repos de ejemplos. Pero siempre con la visión de que sienta que el sitio es Nica.

**Comment by paulomcnally** [comment]
@leftdevel podrías sugerir como **Nicaraguizar** el sitio actual?

**Comment by carloslenondavis** [comment]
@leftdevel Tienes toda la razón en cuanto que ya hay cientos de foros. Pero hasta hoy no he encontrado un foro en donde ademas de chatear y recibir respuestas, se pueda interactuar con código, ejemplo, artículos, con la comunidad, que sea user friendly, etc etc en un mismo contexto. Si ves es genial poder tener todas estas opciones en un solo sitio

**Comment by carloslenondavis** [comment]
@leftdevel a que te refieres cuando dices que el sitio sea Nica?.

**Comment by paulomcnally** [comment]
@hosmelq NextJS nos ayudaría a consumir las APIs de Facebook, Medium, Github... a nivel de back-end para mostrarlo en front-end?

**Comment by hosmelq** [comment]
@paulomcnally Gatsby te genera un sitio estático, con eso tendríamos un render más rápido, se integra muy bien con graphql con el cual podríamos consumir el api de github para cargar los repos.

Podes probarlo https://www.gatsbyjs.org/docs/

**Comment by leftdevel** [comment]
@paulomcnally. Por ejemplo, ir pensando en eventos de node.js aquí en Nicaragua. Podemos hacer un piloto en Managua. En realidad desconozco si ya se hacen. Sería mortal subir fotos de eventos, y publicitar eventos en el futuro, etc.

Tal vez hacerle un pitch a una ONG que esté en Nicaragua y que necesite algún sistema pequeño, y se los damos a guate mojado para fondos para eventos futuros.

## EDIT ##
El código del proyecto lo podemos hacer open source. Y tirar un curso sobre el mismo eventualmente.
Crear un post sobre la ONG, de qué trata el proyecto, cómo js-ni aporta a la comunidad nicaragüense. 
Etc. Aunque tal vez me estoy yendo por las nubes.
## END EDIT ##

@clenondavis. Lo de interactuar con código me parece bien, pero instalar un foro me parece un poco apresurado, pero es sólo mi opinión, no estoy en contra de hacerlo, si alguien se apunta a montarlo bienvenido sea.

**Comment by hosmelq** [comment]
@paulomcnally si, se podría, al final eso es totalmente independiente de next.

**Comment by christopher-ramirez** [comment]
@leftdevel sería genial diferenciar el sitio. Se podría compartir contenido o proyectos hechos por mages de acá. Es una idea.

**Comment by paulomcnally** [comment]
@hosmelq la propuesta es que FacebookEvents, MediumPosts, GithubRepos sean 3 módulos disponibles en #npm, (estoy pensando mejor las cosas), entonces basicamente vamos a requerir renderizar 3 módulos/componentes de react en un index.js (Componente de landing page).

**Comment by paulomcnally** [comment]
@leftdevel pensé que te referías mas a lo que menciona @christopher-ramirez, definitivamente eso lo queremos mejorar, actualmente ya se están haciendo algunas cosas (podes ver en la página en fb que hay un live y algunas fotos), por ahora veamos lo del sitio web y en otro hilo (vamos a pensar la mejor forma de comunicarnos) ver lo de como generamos valor a la comunidad con eventos.

**Comment by carloslenondavis** [comment]
Propongo el uso de un SCRUM dashboard o cualquier KANBAN .e.g trello para las tareas. Así seria mas sencillo las asignaciones y así ver los avances y abierto para el que desee apoyar.  En donde cada board seria relacionado a un proyectos, ejemplo: board para el sitio de Ni, así estén todos los interesados de cada proyecto en el board correspondiente

**Comment by hosmelq** [comment]
@paulomcnally Creo que crear módulos de npm no seria lo mejor, podríamos crear componentes directamente en el repo, si tienen que compartir otros componentes o más cosas seria un poco más complicado la config.

**Comment by hosmelq** [comment]
@clenondavis podemos usar github projects.

**Comment by leftdevel** [comment]
@paulomcnally.
`...pensé que te referías mas a lo que menciona @christopher-ramirez...`

Re: También. Me parece que es algo que se puede lograr rápidamente (quick win). Por ahí tengo un proyectito en phantomjs (casperjs) para mandar saldo de celular via una cuenta de Banpro :D No muy útil para los que no tienen cuenta de banco en Banpro, pero al menos es un quick win : )

**Comment by paulomcnally** [comment]
@hosmelq convenceme. Por qué seria mas complicada la configuración? Estoy pensando en que a otros developers les podría servir esos módulos para sus websites.

**Comment by christopher-ramirez** [comment]
@leftdevel interesante! Para alguien que solo hace sus recardas desde Banpro, como yo, aveces da pereza navegar en el sitio.

**Comment by paulomcnally** [comment]
@clenondavis No lo sé, no somos un equipo de trabajo (opino), si me gusta por que tenemos el norte de que hacer, pero bueno... Github Project es mi voto. 👍

**Comment by hosmelq** [comment]
@paulomcnally si tenemos que compartir cosas entre esos módulos seria tener cosas duplicadas o usar algo como Lerna para manejar multiples proyectos en un repo.

**Comment by paulomcnally** [comment]
@christopher-ramirez todos mis repos js/node van a moverse a **js-ni**. Son bienvenidos los tuyos haha. Avisame si requerís algún permiso/rol. De la misma forma publicar en Medium. (A todos les digo lo mismo).

**Comment by jarbitlira** [comment]
Apoyo la moción de @paulomcnally con los módulos NPM, @hosmelq a que te refieres con cosas duplicadas?? 

Podría hacerse un módulo "core" para lo que sea compartido entre módulos y listo asunto resuelto

**Comment by paulomcnally** [comment]
@hosmelq no creo que tengamos que compartir nada, solo habria que definir el diseño/apariencia default de cada módulo/componente para que se vea bien en el sitio y que otro developer si lo quiere implementar que haga su trabajo con un custom css.

**Comment by hosmelq** [comment]
@jarbitlira  No es la mejor manera de compartir código entre módulos, no se si han trabajado de esa manera eso. No me molesta tenerlos por separado, pero si es así como les dije, seria bueno usar [Lerna](https://github.com/lerna/lerna)

**Comment by carloslenondavis** [comment]
@paulomcnally la idea del foro es tener una sala de chat, que se pueda postear artículos o temas.? tienes en mente montar una plataforma de foro o desarrollarlo desde cero. Porque tenemos la capacidad y recursos suficiente para desarrollar este spa y seria un excelente proyecto de comunidad

**Comment by jarbitlira** [comment]
@hosmelq creo que te refieres al momento de hacer alguna modificación entre modulos si es así, de acuerdo en ese aspecto en el sentido de estar cambiando entre proyectos

**Comment by paulomcnally** [comment]
@hosmelq @jarbitlira no creo que tengamos que lidiar con estar cambiando entre módulos, una vez listo el componente A y probado se implementa en **js-ni/ni**. Un simple update de versión si es que el modulo de modificó. Lo de Lerna no me hace click, creo que es lo que hace `react-router` no?

**Comment by christopher-ramirez** [comment]
@hosmelq no había escuchado de Lerna, pero en su intro habla de que es para Codebases grandes. Lo que entiendo es que estamos hablando es de proyectos hechos por nosotros, los desarrolladores locales y que está será una comunidad para compartirlos.

**Comment by paulomcnally** [comment]
@clenondavis lo del foro no va por ahora. Luego podemos ver opciones/alternativas. Pero lo ideal seria algún servicio, no desarrollarlo.

**Comment by clenondavis** [comment]
@paulomcnally estoy de acuerdo.

**Comment by christopher-ramirez** [comment]
@paulomcnally recuerdo el foro que hiciste para NodeJS Nicaragua.

**Comment by hosmelq** [comment]
Bueno, podemos manejar los módulos en repos separados entonces, igual no tengo inconveniente :P

**Comment by carloslenondavis** [comment]
@paulomcnally siempre pensando en el nuevo rumbo del sitio jsni podemos hacer un mock de propuesta de como puede ser la vr2 del sitio de jsNi. Yo puedo ayudar con esto y así podemos definir las secciones y contenido que podemos ir incluyendo, luego del mock como base podemos crear el prototipo no funcional o diseño. Asi obtenemos un diseño fresco para el sitio.

**Comment by paulomcnally** [comment]
@christopher-ramirez no tenia tiempo para mantenerlo. Por eso mejor buscamos algún servicio, ponemos el feed y si alguien quiere usarlo sale del subdominio ni.js.org.

Si saben de servicios como estos pueden proponer, pero opino que StackOverflow en español perfectamente puede ser usado.

**Comment by christopher-ramirez** [comment]
@paulomcnally sí de hecho por eso lo mencioné. Mantener el desarrollo de un foro no es fácil y consume valiosos recursos.

**Comment by paulomcnally** [comment]
@hosmelq importante mencionar que nuestro hosting es y debe seguir siendo github-pages.

No podemos correr no de ahí, solo hostear el SPA.

Esto debido a que el subdominio apunta a Github Paces y nosotros no manejamos eso, lo maneja la gente de js.org

**Comment by hosmelq** [comment]
@paulomcnally Next no se podria hostear en github, podemos usar gatsby.

**Comment by paulomcnally** [comment]
@hosmelq entonces nos vamos con gatsby.

**Comment by oscarmcm** [comment]
@hosmelq Si podes hostear *Next.js* en github pages, solo tenes que agregar a la configuracion exportar el sitio a estatico, asi no dependes de un server corriendo node.

https://github.com/zeit/next.js/#static-html-export

**Comment by hosmelq** [comment]
No conocía esa opción 😬, bueno ahí esta, el que prefieran usar.

**Comment by oscarmcm** [comment]
@hosmelq https://www.meetup.com/es-ES/gdgmanagua/events/248927736/ 😉

**Comment by hosmelq** [comment]
@oscarmcm yo lo use en la v2, para ese tiempo todavía no tenían ese soporte, uno de estos días le pego una leída a la doc y vamos a ver si puedo pasar por el meetup.

**Comment by juanpicado** [comment]
Chicos, deberian seriamente sentarse y pensar cuales son sus objetivos principales para su comunidad, IMHO veo muchos palos de ciego, foros, paginas, api. Porque quieren reinvetar la rueda? Los eventos es algo positivo, pero, gastar recursos en paginas aka foros cuando tienes meetup.com (cc @oscarmcm ) que ofrece todo lo que necesitas es un poco sin sentido. 

Yo les recomendaria, primero, lograr que la gente acuda a sus eventos y despues, preocupense por marketing y publicidad. Sin gente no hay comunidad.

**Comment by paulomcnally** [comment]
@juanpicado ambas cosas se pueden realizar a la vez, no veo por qué no marketing, publicidad y eventos a la vez.

Con respecto a los eventos no le estoy preguntando a todos, pregunto a miembros específicos si pueden dar una charla. El sábado tenemos un evento pero eso se planea mas a lo interno por ahora.

Al final cuando toca tomar una escoba para barrer el local luego del evento son raros y contados los que quedan.

**Comment by juanpicado** [comment]
> Al final cuando toca tomar una escoba para barrer el local luego del evento son raros y contados los que quedan.

Pues ponte hacer un foro, veras cuantos quedan despues de 1 mes. Ni la escoba. 

> Con respecto a los eventos no le estoy preguntando a todos, pregunto a miembros específicos si pueden dar una charla.

👍 ( me encantaria si no viviera tan lejos )

> no veo por qué no marketing, publicidad y eventos a la vez.

Si un sitio web toma mas de 1 hora, entonces, estas gastando demasiados recursos.

**Comment by carloslenondavis** [comment]
@juanpicado comparto contigo en la parte que debemos como comunidad nicaragüense y eso te incluye a ti, en generar y dar mas publicidad a los eventos y demás actividades, asi que los participantes crezcan. Pero si ves es un buen comienzo, los chicos estamos tratando es de promover un espacio en donde como Nic y fuera de Nic, encontrar codigo y ayuda, promoviendo asi el compartir conocimiento. Sería bueno que propongas ideas y sugerencias sobre como se puede hacer que todos los desarrolladores en JS puedan visitar los eventos y se que tienes buenas ideas que quizás puedas compartirla.

**Comment by paulomcnally** [comment]
@juanpicado si ves el hilo lo del foro es prioridad baja.

Para los eventos de requieren charlas, siempre he pensado que una de tu parte es bienvenida, aun que estés en el otro extremo del mundo. Es opción vía hangout.

No se que clavo hay con gastar recursos. Si una o 100 personas meten mano en el sitio web no se afecta nada, no afectas a nadie.

Dejame entender que esta mal en querer tener un sitio con blog, eventos, repos.

**Comment by carloslenondavis** [comment]
> Chicos, deberian seriamente sentarse y pensar cuales son sus objetivos principales para su comunidad, IMHO veo muchos palos de ciego, foros, paginas, api. Porque quieren reinvetar la rueda? Los eventos es algo positivo, pero, gastar recursos en paginas aka foros cuando tienes meetup.com (cc @oscarmcm ) que ofrece todo lo que necesitas es un poco sin sentido.

Si te fijas todas las ideas llevan a un solo objetivo el compartir y promover conocimiento sobre JS. Claro lo que si debe mejorar son los mecanismo y medios para poder analizar y ejecutar cada idea que se dan en estas platicas. Pero a mi parecer yo estoy muy contento, porque por lo menos se tiene la iniciativa de siempre compartir código y de mas temas que apoyen a los oyentes. Y la actitud de cada uno es además de criticar (que es bueno) también bien aportar ideas y tener iniciativas. En lo personal, nadie me pidió que subiera ejemplos de graphql y jest, simplemente pedi a @paulomcnally  acceso y lo subí. Así aporto un grano a la comunidad.

**Comment by paulomcnally** [comment]
Creo que @juanpicado no leyó todo el hilo :)

Al final si @juanpicado opina que ni la escoba se queda pero si @clenondavis  quiere hacer el foro nadie lo detiene y yo seria uno de los mas activos en el foro. :)

**Comment by luchonetvv** [comment]
talves la parte que tiene que ver con Nicaragua sea algo asi como dar
soluciona alguna problematica enfocar el esfuerzo en construir una
herramienta de uso para los nicaraguenses eso creo que puede ser, abordar
un problema y construir un proyecto a partir de ello, pienso que quiere dar
a entender

**Comment by paulomcnally** [comment]
Siempre he estado en pro de eso @luchonetvv es por eso que estoy esperando el repo de @christopher-ramirez :)

**Comment by gacsnic** [comment]
Seria muy bueno lo del foro, aunque hay muchos en la web no estaria mal un foro regionalizado, claro sin el saludo que nos caracterisa

**Comment by paulomcnally** [comment]
En resumen:

# Website: 

https://ni.js.org/

# Blog

https://medium.com/javascript-nicaragua

# YouTube

https://www.youtube.com/channel/UC2qZ0Fvw9NNN5ROdKydeV8Q

Para nuevas propuestas propongo abrir otro hilo/issue.
