### ISSUE TITLE
website: Implementar eventos desde el API de eventos de páginas de facebook

### ISSUE THREAD

**Issue by paulomcnally** [js-ni/ni#14]
Propongo que la página de eventos no exista (https://ni.js.org/events), si no que los eventos se muestren en la página de inicio y sean obtenidos desde al API de facebook https://developers.facebook.com/docs/graph-api/reference/page/events/.

**Comment by carloslenondavis** [comment]
@paulomcnally  necesitas una mano me avisas.

**Comment by paulomcnally** [comment]
Se requiere crear un componente en React llamado FacebookEvents.

Este debería ser implementado en la página de inicio.

Este componente deberá tener toda la lógica de comunicación con Facebook para obtener la lista de eventos.

Preferiblemente que se cree un módulo y se publique en #npm y obvio el código fuente en un repositorio de js-ni.

**Comment by paulomcnally** [comment]
@clenondavis claro. Si te lo vas a tirar vos es bienvenido.

**Comment by carloslenondavis** [comment]
@paulomcnally excelente, pero me gustaría hecharle mano al nuevo horizonte de jsNi. jajajjajjaja. Por cierto esta interesante la platica jaajaj

**Comment by paulomcnally** [comment]
Esto ya lo estamos haciendo de forma manual.
