### ISSUE TITLE
website: Implementar feed de publicaciones en el blog de medium.

### ISSUE THREAD

**Issue by paulomcnally** [js-ni/ni#15]
Seria bueno que en la página de inicio tengamos un feed de las publicaciones más recientes del blog de medium.

https://medium.com/javascript-nicaragua/latest?format=json

**Comment by paulomcnally** [comment]
Se requiere crear un componente en React llamado **MediumPosts**.

Este debería ser implementado en la página de inicio.

Este componente deberá tener toda la lógica de comunicación con Medium para obtener la lista de publicaciones.

Preferiblemente que se cree un módulo y se publique en #npm y obvio el código fuente en un repositorio de js-ni.

**Comment by paulomcnally** [comment]
Se montó un server con CORS habilitados para poder obtener los artículos más recientes desde Medium.

**Repo**: https://github.com/js-ni/blog-api
**Server URL**: https://js-ni-blog-api.herokuapp.com/

**Comment by paulomcnally** [comment]
Actualmente se consume un archivo .json almacenado en el proyecto. Se debe reemplazar usando `fetch` o `axios` (https://github.com/axios/axios).



<img width="1087" alt="captura de pantalla 2018-10-29 a la s 11 55 13 a m" src="https://user-images.githubusercontent.com/181533/47669885-82f9da80-db71-11e8-9a37-b81b80f77b57.png">

**Comment by hosmelq** [comment]
@paulomcnally yo voy a trabajar esto.

**Comment by paulomcnally** [comment]
Copiado @hosmelq .

**Comment by paulomcnally** [comment]
Resuelto en https://github.com/js-ni/js-ni-medium-posts.

Excelente trabajo @hosmelq.

👍
