### ISSUE TITLE
Blog - Artículos no están cargando

### ISSUE THREAD

**Issue by carloslenondavis** [js-ni/ni#22]
### Step

1. Abrir sitio js-ni
2. Ir a la sección de artículos
3. Mensaje de CORS

Ver siguiente captura de pantalla
<img width="1316" alt="screen shot 2018-10-30 at 8 48 59 am" src="https://user-images.githubusercontent.com/4239218/47726802-d5460480-dc20-11e8-8c66-c4fb92359f78.png">

**Comment by paulomcnally** [comment]
Gracias @clenondavis, resuelto acá -> https://github.com/js-ni/blog-api/commit/af343f24cb5cdfe3e616563d875e0457ed7d0854
