### ISSUE TITLE
[js-ni/ni] Google apikey exposed on GitHub

### ISSUE THREAD

**Issue by paulomcnally** [js-ni/ni#30]
@hosmelq Github
[Gmail - [js-ni_ni] Google apikey exposed on GitHub.pdf](https://github.com/js-ni/ni/files/3176004/Gmail.-.js-ni_ni.Google.apikey.exposed.on.GitHub.pdf)
 nos advirtió que se exponía la llave de mapas de google.

**Comment by hosmelq** [comment]
No hay problema, la llave esta restrigida para que solo funcione bajo el dominio.
