### ISSUE TITLE
Error al cargar los mapas

### ISSUE THREAD

**Issue by paulomcnally** [js-ni/ni#32]
@hosmelq cada que hago nuevo deploy se rompe lo de los mapas, podrías agregar en el README.md los pasos a seguir para solucionar esto? Así se hace lo que se deba hacer pre o post deploy.

**Comment by hosmelq** [comment]
Esta pasando porque no tienes la key de google maps al hacer el deploy, tienes que crear un .env y agregarla.

Esta la otra opción de agregarla en duro, al final la tengo que funcione solo para el sitio.
