### ISSUE TITLE
Implementar git-flow para respetar el lanzamiendo automático de la rama master

### ISSUE THREAD

**Issue by paulomcnally** [js-ni/ni#4]
Todo lo que cae a master automáticamente se lanza a heroku.

Es por eso que les propongo implementemos el git-flow para que todo caiga a develop y cuando caracteristicas esten listas caigan a master.

Todos podriamos hacer merge a master desde develop siempre y cuando develop este 100% funcional.

¿Estamos de acuerdo?
@oscarmcm @hosmelq

**Comment by hosmelq** [comment]
Me parece perfecto.
