### ISSUE TITLE
Logo sitio web - header

### ISSUE THREAD

**Issue by paulomcnally** [js-ni/ni#8]
![Logo JavaScript.com](https://www.javascript.com/images/pages/shared/logo.svg)

Se requiere tener un logo idéntico a ese pero en vez de `javascript.com` debería ser `ni.js.org`.

Ojo! El color del texto es blanco.

Las dimensiones son las que tiene el logo mencionado o menor de ancho.

**Comment by oscarmcm** [comment]
@paulomcnally puedo conseguir el logo. te lo paso en los proximos dias 👍

**Comment by paulomcnally** [comment]
Loco! Es tu hermano, préstale un short o una camisa y que te haga el logo hoy.

**Comment by paulomcnally** [comment]
Seguimos esperando ese logo @oscarmcm 👎

**Comment by burzumumbra** [comment]
@oscarmcm confirma si te sacas vos el Logo, sino resuelvo yo el Logo+Favicon.

**Comment by jarbitlira** [comment]
Seria tuani que el logo haga referencia al País algo con lagos y volcanes :D

**Comment by oscarmcm** [comment]
@burzumumbra gracias por tu colaboracion ¡Adelante!

**Comment by leogg** [comment]
@burzumumbra 
[jsni.logo.svg.zip](https://github.com/js-ni/ni/files/1399143/jsni.logo.svg.zip)

**Comment by leogg** [comment]
El de CostaRicaJs https://goo.gl/N7tRwX

**Comment by oscarmcm** [comment]
@burzumumbra hace tiempo hice algo para nodenica > https://github.com/nodenica/nodenica-website/issues/26 Cc @leogg

**Comment by burzumumbra** [comment]
@leogg Algo como el de CostaRicaJs no se si pueda hacer, pero vamo a ver.

**Comment by jarbitlira** [comment]
@oscarmcm La opción 2 esta buena

**Comment by paulomcnally** [comment]
Nos quedamos con https://github.com/js-ni/ni/issues/8#issuecomment-337960265 para el sitio.

Podríamos tener otro logo para stickers y puede ser otro issue.

Gracias @leogg

**Comment by dianalih** [comment]
Hola McNally, aqui el logo. 
[jsni.zip](https://github.com/js-ni/ni/files/1402653/jsni.zip)

**Comment by paulomcnally** [comment]
Gracias @LissTrujillo
